---
title: "Ischemic heart disease mortality rates and the interaction of sex, time, and socioeconomic developemnt"
subtitle: "An Analysis of the Global Burden of Disease Study"
format: 
  html:
    toc: true
    toc-expand: true
    toc-location: body
date: 5-23-2024
theme: lightly
author:
  - name: "Ahmed Sayed (asu.ahmed.sayed@gmail.com)"
    affiliations: "Ain Shams University, Faculty of Medicine"
embed-resources: true
toc: true
toc-expand: 2
toc-title: Contents
page-layout: full
code-fold: true
editor: visual
---

```{r}
load("Data for Rendering.RData")
library(dplyr)
library(stringr)
```

**Included countries and territories**

Of the `r x %>% filter(sex == "Male") %>% pull(location) %>% unique() %>% length` unique countries and territories included in the GBD study, all had available data on SDI (median in 1980 and 2021: `r x %>% filter(sex == "Male" & !is.na(sdi)) %>% filter(year == 2021) %>% pull(sdi) %>% quantile() %>% {.[3]} %>% round(2)` and `r x %>% filter(sex == "Male" & !is.na(sdi)) %>% filter(year == 1980) %>% pull(sdi) %>% quantile() %>% {.[3]} %>% round(2)` respectively; interquartile range: `r x %>% filter(sex == "Male" & !is.na(sdi)) %>% filter(year == 1980) %>% pull(sdi) %>% quantile() %>% {.[2]} %>% round(2)` to `r x %>% filter(sex == "Male" & !is.na(sdi)) %>% filter(year == 1980) %>% pull(sdi) %>% quantile() %>% {.[4]} %>% round(2)` and `r x %>% filter(sex == "Male" & !is.na(sdi)) %>% filter(year == 2021) %>% pull(sdi) %>% quantile() %>% {.[2]} %>% round(2)` to `r x %>% filter(sex == "Male" & !is.na(sdi)) %>% filter(year == 2021) %>% pull(sdi) %>% quantile() %>% {.[4]} %>% round(2)` respectively) and were included in this analysis.

**Sex-stratified trends of IHD mortality across different SDI levels**

**Figure 1** shows the sex-stratified age-adjusted mortality rates (per 100,000) from 1980 to 2021 at low, average, and high SDI (defined as the 20^th^, 50^th^, and 80^th^ percentiles of SDI for each year) averaged over countries and territories. In 1980, mortality rates for females were relatively similar across different SDI settings (AAMR per 100,000: `r ihd_mm_trends %>% filter(year == 1980 & sex == "Female" & sdi_level == "low_sdi") %>% pull(pe) %>% round(0)` \[95% CI: `r ihd_mm_trends %>% filter(year == 1980 & sex == "Female" & sdi_level == "low_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 1980 & sex == "Female" & sdi_level == "low_sdi") %>% pull(uci) %>% round(0)`\], `r ihd_mm_trends %>% filter(year == 1980 & sex == "Female" & sdi_level == "average_sdi") %>% pull(pe) %>% round(0)`, \[95% CI: `r ihd_mm_trends %>% filter(year == 1980 & sex == "Female" & sdi_level == "average_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 1980 & sex == "Female" & sdi_level == "average_sdi") %>% pull(uci) %>% round(0)`\] `r ihd_mm_trends %>% filter(year == 1980 & sex == "Female" & sdi_level == "high_sdi") %>% pull(pe) %>% round(0)` \[95% CI: `r ihd_mm_trends %>% filter(year == 1980 & sex == "Female" & sdi_level == "high_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 1980 & sex == "Female" & sdi_level == "high_sdi") %>% pull(uci) %>% round(0)`\] in low, average, and high SDI levels respectively). In contrast, male mortality rates were lowest in low SDI settings (AAMR per 100,000: `r ihd_mm_trends %>% filter(year == 1980 & sex == "Male" & sdi_level == "low_sdi") %>% pull(pe) %>% round(0)` \[95% CI: `r ihd_mm_trends %>% filter(year == 1980 & sex == "Male" & sdi_level == "low_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 1980 & sex == "Male" & sdi_level == "low_sdi") %>% pull(uci) %>% round(0)`\]), higher in average SDI settings (AAMR per 100,000: `r ihd_mm_trends %>% filter(year == 1980 & sex == "Male" & sdi_level == "average_sdi") %>% pull(pe) %>% round(0)` \[95% CI: `r ihd_mm_trends %>% filter(year == 1980 & sex == "Male" & sdi_level == "average_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 1980 & sex == "Male" & sdi_level == "average_sdi") %>% pull(uci) %>% round(0)`\]), and highest in high SDI settings (AAMR per 100,000: `r ihd_mm_trends %>% filter(year == 1980 & sex == "Male" & sdi_level == "high_sdi") %>% pull(pe) %>% round(0)` \[95% CI: `r ihd_mm_trends %>% filter(year == 1980 & sex == "Male" & sdi_level == "high_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 1980 & sex == "Male" & sdi_level == "high_sdi") %>% pull(uci) %>% round(0)`\]).

Temporal changes in age-adjusted mortality rates since 1980 and up to 2021 are shown in **Figure 2**. In low SDI settings, mortality rates by 2021 had declined by a small and statistically non-significant decline for females (`r ihd_trends %>% filter(compared_to == 2021 & sex == "Female" & sdi_level == "low_sdi") %>% pull(pe_ci)`) and increased by `r ihd_trends %>% filter(compared_to == 2021 & sex == "Male" & sdi_level == "low_sdi") %>% pull(pe) %>% {(. - 1)*100} %>% round(0)`% for males (`r ihd_trends %>% filter(compared_to == 2021 & sex == "Male" & sdi_level == "low_sdi") %>% pull(pe_ci)`). According, mortality rates in 2021 had declined to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Female" & sdi_level == "low_sdi") %>% pull(pe) %>% round(0)` per 100,000 for females (95% CI: `r ihd_mm_trends %>% filter(year == 2021 & sex == "Female" & sdi_level == "low_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Female" & sdi_level == "low_sdi") %>% pull(uci) %>% round(0)`) and increased to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Male" & sdi_level == "low_sdi") %>% pull(pe) %>% round(0)` per 100,000 for males (95% CI: `r ihd_mm_trends %>% filter(year == 2021 & sex == "Male" & sdi_level == "low_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Male" & sdi_level == "low_sdi") %>% pull(uci) %>% round(0)`) in settings with a low SDI. In contrast, in settings with an average SDI, mortality rates declined by more than 25% for both females (`r ihd_trends %>% filter(compared_to == 2021 & sex == "Female" & sdi_level == "average_sdi") %>% pull(pe_ci)`) and males (`r ihd_trends %>% filter(compared_to == 2021 & sex == "Male" & sdi_level == "average_sdi") %>% pull(pe_ci)`). According, mortality rates in 2021 had decreased to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Female" & sdi_level == "average_sdi") %>% pull(pe) %>% round(0)` per 100,000 for females (95% CI: `r ihd_mm_trends %>% filter(year == 2021 & sex == "Female" & sdi_level == "average_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Female" & sdi_level == "average_sdi") %>% pull(uci) %>% round(0)`) and to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Male" & sdi_level == "average_sdi") %>% pull(pe) %>% round(0)` per 100,000 for males (95% CI: `r ihd_mm_trends %>% filter(year == 2021 & sex == "Male" & sdi_level == "average_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Male" & sdi_level == "average_sdi") %>% pull(uci) %>% round(0)`). In high SDI settings, mortality rates declined by more than 50% for females (`r ihd_trends %>% filter(compared_to == 2021 & sex == "Female" & sdi_level == "high_sdi") %>% pull(pe_ci)`) and males (`r ihd_trends %>% filter(compared_to == 2021 & sex == "Male" & sdi_level == "high_sdi") %>% pull(pe_ci)`). According, mortality rates in 2021 had decreased to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Female" & sdi_level == "high_sdi") %>% pull(pe) %>% round(0)` per 100,000 for females (95% CI: `r ihd_mm_trends %>% filter(year == 2021 & sex == "Female" & sdi_level == "high_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Female" & sdi_level == "high_sdi") %>% pull(uci) %>% round(0)`) and to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Male" & sdi_level == "high_sdi") %>% pull(pe) %>% round(0)` per 100,000 for males (95% CI: `r ihd_mm_trends %>% filter(year == 2021 & sex == "Male" & sdi_level == "high_sdi") %>% pull(lci) %>% round(0)` to `r ihd_mm_trends %>% filter(year == 2021 & sex == "Male" & sdi_level == "high_sdi") %>% pull(uci) %>% round(0)`).

**Sex-stratified association of low SDI with excess IHD mortality**

**Figures 3A-C & Figures 4A-C** show the sex-stratified association between SDI and mortality rates at the beginning (1980), midpoint (2000), and end (2021) of the study period, respectively. Rate ratios are presented in **Figure 3** and absolute differences are presented in **Figure 4**. In 1980 (**Figure 3A**), the association between SDI and IHD mortality did not favor high SDI settings. Comparing low versus high SDI settings, mortality rates were relatively similar for females (rate ratio: `r overall$begin$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe_ci) %>% str_remove_all("\\)|\\(") %>% str_replace(" 95", "; 95")`) but `r overall$begin$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe) %>% {(1 - .)*100} %>% round(0)`% lower for males (rate ratio: `r overall$begin$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe_ci) %>% str_remove_all("\\)|\\(") %>% str_replace(" 95", "; 95")`). By 2000 (**Figure 3B**), disparities in IHD mortality by SDI started to become evident for females, whereas males in lower SDI settings no longer had lower mortality rates compared to their high SDI counterparts. Compared to a high SDI setting, a low SDI setting was associated with a `r overall$mid$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe_ci) %>% word(., 1)`-fold elevation in mortality rates among males and a greater `r overall$mid$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe_ci) %>% word(., 1)`-fold elevation among females, such that the associated increase in mortality was `r 100*(round(overall$mid$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe)/overall$mid$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe), 2) - 1)`% greater in females compared to males (*P* for difference in rate ratio by sex: `r overall$mid$ratio_ratios_p`). By 2021 (**Figure 3C**), disparities grew larger and were still more pronounced in females. Compared to a high SDI setting, a low SDI setting was associated with a `r overall$end$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe_ci) %>% word(., 1)`-fold elevation in mortality rates among males and a greater `r overall$end$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe_ci) %>% word(., 1)`-fold elevation among females, such that the associated increase in mortality was `r 100*(round(overall$end$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe)/overall$end$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe), 2) - 1)`% greater in females compared to males (*P* for difference in rate ratio by sex: `r overall$end$ratio_ratios_p`).

As **Figure 3B and 3C** show, the extent to which SDI was associated with greater excess mortality among females was more pronounced at SDIs near the lowermost end of the spectrum. Compared to a (high) SDI at the 80^th^ percentile in 2021, an SDI at the 60^th^ percentile was associated with a `r overall$end$contrasts %>% filter(pct == "60%" & sex == "Male") %>% pull(pe_ci) %>% word(., 1)`-fold elevation in mortality rates among males and a slightly greater `r overall$end$contrasts %>% filter(pct == "60%" & sex == "Female") %>% pull(pe_ci) %>% word(., 1)`-fold elevation among females, such that the associated increase in mortality was only `r 100*(round(overall$end$contrasts %>% filter(pct == "60%" & sex == "Female") %>% pull(pe)/overall$end$contrasts %>% filter(pct == "60%" & sex == "Male") %>% pull(pe), 2) - 1)`% greater in females compared to males. In contrast, an SDI at the 40^th^ percentile was associated with a `r overall$end$contrasts %>% filter(pct == "40%" & sex == "Male") %>% pull(pe_ci) %>% word(., 1)`-fold elevation in mortality rates among males and a greater `r overall$end$contrasts %>% filter(pct == "40%" & sex == "Female") %>% pull(pe_ci) %>% word(., 1)`-fold elevation among females, such that the associated increase in mortality was `r 100*(round(overall$end$contrasts %>% filter(pct == "40%" & sex == "Female") %>% pull(pe)/overall$end$contrasts %>% filter(pct == "40%" & sex == "Male") %>% pull(pe), 2) - 1)`% greater in females compared to males. Further and as above, an SDI at the 20^th^ percentile was associated with a `r overall$end$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe_ci) %>% word(., 1)`-fold elevation in mortality rates among males and a greater `r overall$end$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe_ci) %>% word(., 1)`-fold elevation among females, such that the associated increase in mortality was `r 100*(round(overall$end$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe)/overall$end$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe), 2) - 1)`% greater in females compared to males.

Similar findings were observed when using absolute differences (**Figure 4A-C)**, with the exception that sex disparities in lower SDI settings were worse for males than for females in 2021 (**Figure 4C)**. Results of the Bayesian analysis incorporating uncertainty in mortality rates showed similar findings (**eFigures 1 & 2)**.

**Sex-stratified association of low SDI with risk factor-attributable excess IHD mortality**

**eFigures 3A-C to 5A-C** show mortality elevations attributable to the three level 1 risk factor categories (behavioral risk factors, metabolic risk factors, and environmental/occupational risk factors). The excess contemporary mortality rates associated with a lower SDI seen with behavioral risk factor and metabolic risk factor-attributable IHD mortality were similar in their temporal patterns and magnitude to overall IHD mortality. In contrast, the excess contemporary mortality seen with environmental/occupational risk factor-attributable IHD mortality was more pronounced in magnitude. For brevity, only mortality rates in 2021 are discussed here and the reader is referred to **eFigures 3A-B to 5A-B** for 1980 and 2000.

Compared to a high SDI setting, a low SDI setting was associated with a `r subgroups$behavioral$end$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe_ci) %>% word(., 1)`-fold elevation in mortality rates attributable to behavioral risk factors among males and a greater `r subgroups$behavioral$end$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe_ci) %>% word(., 1)`-fold elevation among females, such that the associated increase in mortality was `r 100*(round(subgroups$behavioral$end$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe)/subgroups$behavioral$end$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe), 2) - 1)`% greater in females compared to males (*P* for difference in rate ratio by sex: `r subgroups$behavioral$end$ratio_ratios_p`). For mortality rates attributable to metabolic risk factors, a low SDI setting was associated with a `r subgroups$mets$end$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe_ci) %>% word(., 1)`-fold elevation in mortality rates factors among males and a greater `r subgroups$mets$end$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe_ci) %>% word(., 1)`-fold elevation among females, such that the associated increase in mortality was `r 100*(round(subgroups$mets$end$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe)/subgroups$mets$end$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe), 2) - 1)`% greater in females compared to males (*P* for difference in rate ratio by sex: `r subgroups$mets$end$ratio_ratios_p`).

The association between a lower SDI and excess mortality was more pronounced for IHD mortality attributable to environmental/occupational risk factors. A low SDI setting was associated with a `r subgroups$envocc$end$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe_ci) %>% word(., 1)`-fold elevation in mortality rates factors among males and a `r subgroups$envocc$end$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe_ci) %>% word(., 1)`-fold elevation among females, such that the associated increase in mortality was `r 100*(1 - (round(subgroups$envocc$end$contrasts %>% filter(pct == "20%" & sex == "Female") %>% pull(pe)/subgroups$envocc$end$contrasts %>% filter(pct == "20%" & sex == "Male") %>% pull(pe), 2)))`% lower in females compared to males, though this difference was not statistically significant (*P* for difference in rate ratio by sex `r subgroups$envocc$end$ratio_ratios_p`).

**Comparison to trends in all-cause mortality.**

Temporal changes in all-cause mortality are shown in **eFigure 6**. Unlike IHD mortality, which did not decline in low SDI settings, all-cause mortality in low SDI settings declined for both females (`r acm_trends %>% filter(compared_to == 2021 & sex == "Female" & sdi_level == "low_sdi") %>% pull(pe_ci)`) and males (`r acm_trends %>% filter(compared_to == 2021 & sex == "Male" & sdi_level == "low_sdi") %>% pull(pe_ci)`). Further, unlike IHD, where SDI-based disparities were not initially evident in 1980 but developed over time, disparities in all-cause mortality were already evident in 1980 for both females (rate ratio: `r overall$begin$contrasts_acm %>% filter(pct == "20%" & sex == "Female") %>% pull(pe_ci) %>% str_remove_all("\\)|\\(") %>% str_replace(" 95", "; 95")`) and males (rate ratio: `r overall$begin$contrasts_acm %>% filter(pct == "20%" & sex == "Male") %>% pull(pe_ci) %>% str_remove_all("\\)|\\(") %>% str_replace(" 95", "; 95")`) (**eFigure 7**).
